### ISSUE TITLE
No longer possible to log out

### ISSUE THREAD

**Issue by erkannt** [Makespace/members-app#46]
When I'm logged in the navbar shows be the 'Log in' link instead of 'Log out'. Logging out is therefore impossible.

Given that the only page we display to non-logged in users in the log-in page I would suggest we always display the 'Log out' link in the navbar. Treat the log-in page as an edge case and don't use the page-template on it. This would mean that the pages no longer need to carry around information of whether a user is logged in or not. That responsibility would live solely in the http handlers.

**Comment by Lan2u** [comment]
> Treat the log-in page as an edge case and don't use the page-template on it.

Makes sense

**Comment by Lan2u** [comment]
It also seems possible to 'log-in' when already logged in - this should auto redirect away

**Comment by Lan2u** [comment]
> > Treat the log-in page as an edge case and don't use the page-template on it.
> 
> Makes sense

Looking at this again - it might instead of getting rid of the user from the page template embrace it more and use it to display something indicated who is currently logged in

**Comment by Lan2u** [comment]
![image](https://github.com/user-attachments/assets/b4294240-ec02-4e51-a8aa-524930a9ec11)

Added the avatar of the currently logged in user to the top right. Fixed the log-out not displaying. Modified a few minor things with redirecting to the login page / redirecting to the home page when it makes sense (i.e. if you go to the login page and are already logged in then we now redirect to the home page)
