### ISSUE TITLE
Super users can no longer see member email address on members page

### ISSUE THREAD

**Issue by erkannt** [Makespace/members-app#47]
When I go to /members as a super user I only see ***** instead of email

**Comment by Lan2u** [comment]
will look at this evening

**Comment by Lan2u** [comment]
https://github.com/Makespace/members-app/issues/41

**Comment by Lan2u** [comment]
As a normal member
![image](https://github.com/user-attachments/assets/633925f8-f014-423e-aa79-af228ceb24c3)

As a super user
![image](https://github.com/user-attachments/assets/a23d47bd-2466-41ba-a831-0d82a4d246b4)
