### ISSUE TITLE
Coming from an outside domain hits login flow

### ISSUE THREAD

**Issue by chromy** [Makespace/members-app#64]
Clicking a link in google sheets hits the login flow but navigating directly is fine.
For example: https://makespace-app.fly.dev/areas/8d1ad72e-dfa4-452d-956e-4a656c0f3b4d

**Comment by erkannt** [comment]
According to @chromy this is due to our cookie security settings.

Options:

- be less strict with cookies
- add a redirect?

**Comment by chromy** [comment]
```
The lax value provides a reasonable balance between security and usability for websites that want to maintain user’s logged-in session after the user arrives from an external link. In the above GitHub scenario, the session cookie would be allowed when following a regular link from an external website while blocking it in CSRF-prone request methods (e.g. POST).
```

`https://owasp.org/www-community/SameSite`

Maybe just `sameSite: 'strict'` -> `sameSite: 'lax'`

**Comment by erkannt** [comment]
This issue is probably also preventing people signing the owner agreement.

**Comment by chromy** [comment]
Seems to work now! https://makespace-app.fly.dev/equipment/22aeae84-31ad-4a60-ab5b-c973ddf5d4a3 (the area link from OP still doesn't work but now because that page was removed)
